[package]
name = "text-editor"
version = "0.1.0"
authors = ["Franciszek Madej <f.madej@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1"
